; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2 on Sun Nov 25 2018 19:09:02 GMT-0500 (Eastern Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


