; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v2 on Sun Nov 25 2018 19:09:03 GMT-0500 (Eastern Standard Time)
M83            ; relative extruder moves
G1 E-10 F3600  ; retract 10mm of filament
G91            ; relative positioning
G1 Z5 F360     ; lift Z by 5mm
G90            ; absolute positioning
G1 X0 Y150 F6000 ; go to X=0 Y=150

