; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Sun Nov 25 2018 19:09:03 GMT-0500 (Eastern Standard Time)

