; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Sun Nov 25 2018 19:09:03 GMT-0500 (Eastern Standard Time)
; Wait for set temperatures to be reached
M116 P0

